// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`

Future<void> addLocalPack({
  required String repoPath,
  required FlutterLocalPackConfig config,
}) => RustLib.instance.api.crateApiCommandsAddLocalPackAddLocalPack(
  repoPath: repoPath,
  config: config,
);

class FlutterLocalPackConfig {
  final String name;
  final String? parent;

  const FlutterLocalPackConfig({required this.name, this.parent});

  @override
  int get hashCode => name.hashCode ^ parent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterLocalPackConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          parent == other.parent;
}
