// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<RepoConfig> initFromRemote({
  required String remote,
  required String targetDir,
}) => RustLib.instance.api.crateApiCommandsInitFromRemoteInitFromRemote(
  remote: remote,
  targetDir: targetDir,
);

class RepoConfig {
  final String name;
  final String description;
  final Set<String> packs;

  const RepoConfig({
    required this.name,
    required this.description,
    required this.packs,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ packs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          packs == other.packs;
}
