// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<RepoConfig> initFromRemote({
  required String remote,
  required String targetDir,
}) => RustLib.instance.api.crateApiCommandsInitFromRemoteInitFromRemote(
  remote: remote,
  targetDir: targetDir,
);

class RepoConfig {
  final String name;
  final String description;
  final Set<String> packs;
  final RepoCustomization? customization;

  const RepoConfig({
    required this.name,
    required this.description,
    required this.packs,
    this.customization,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      packs.hashCode ^
      customization.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          packs == other.packs &&
          customization == other.customization;
}

class RepoCustomization {
  final (int, int, int, int)? color;

  const RepoCustomization({this.color});

  @override
  int get hashCode => color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoCustomization &&
          runtimeType == other.runtimeType &&
          color == other.color;
}
