// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> launch({required String repoDir, required String packName}) =>
    RustLib.instance.api.crateApiCommandsLaunchLaunch(
      repoDir: repoDir,
      packName: packName,
    );
