// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `Ok(None)` on platforms that need no setup, so the Dart side can render
/// nothing without special-casing an error.
Future<LinuxSetupInfo?> linuxSetupInfo({required String repoDir}) => RustLib
    .instance
    .api
    .crateApiCommandsLinuxSetupLinuxSetupInfo(repoDir: repoDir);

/// The one-time Steam setup a repo needs on Linux.
///
/// Declared and generated on every platform so the committed Dart bindings
/// under `ui/lib/src/rust` are identical whichever machine ran the codegen;
/// only the body is platform-specific.
class LinuxSetupInfo {
  final SteamFlavour steamFlavour;
  final String armaInstallDir;

  /// Paste into Steam → Arma 3 → Properties → Launch Options. `None` when
  /// Steam needs nothing set up.
  final String? launchOptions;

  /// The roots embedded in `launch_options`, listed separately for display.
  final List<String> pressureVesselRoots;

  /// Host paths needing a Flatpak grant.
  final List<String> flatpakRoots;

  /// The command granting `flatpak_roots`. `None` for native Steam, or when
  /// nothing sits outside the sandbox.
  final String? flatpakOverrideCommand;

  const LinuxSetupInfo({
    required this.steamFlavour,
    required this.armaInstallDir,
    this.launchOptions,
    required this.pressureVesselRoots,
    required this.flatpakRoots,
    this.flatpakOverrideCommand,
  });

  @override
  int get hashCode =>
      steamFlavour.hashCode ^
      armaInstallDir.hashCode ^
      launchOptions.hashCode ^
      pressureVesselRoots.hashCode ^
      flatpakRoots.hashCode ^
      flatpakOverrideCommand.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinuxSetupInfo &&
          runtimeType == other.runtimeType &&
          steamFlavour == other.steamFlavour &&
          armaInstallDir == other.armaInstallDir &&
          launchOptions == other.launchOptions &&
          pressureVesselRoots == other.pressureVesselRoots &&
          flatpakRoots == other.flatpakRoots &&
          flatpakOverrideCommand == other.flatpakOverrideCommand;
}

enum SteamFlavour { native, flatpak }
