// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<PackDisplayInfo> loadPackDisplay({
  required String repoPath,
  required String packName,
}) => RustLib.instance.api.crateApiCommandsLoadPackDisplayLoadPackDisplay(
  repoPath: repoPath,
  packName: packName,
);

/// The subset of a pack's config the UI needs to display it.
class PackDisplayInfo {
  final String name;
  final String description;

  /// File name of the pack's icon inside the repo's `media/` directory.
  final String? icon;

  const PackDisplayInfo({
    required this.name,
    required this.description,
    this.icon,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackDisplayInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          icon == other.icon;
}
