// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<String>> getLaunchParams({
  required String repotPath,
  required String packName,
}) => RustLib.instance.api.crateApiCommandsParamsGetLaunchParams(
  repotPath: repotPath,
  packName: packName,
);

Future<void> setLaunchParams({
  required String repotPath,
  required String packName,
  required List<String> launchParams,
}) => RustLib.instance.api.crateApiCommandsParamsSetLaunchParams(
  repotPath: repotPath,
  packName: packName,
  launchParams: launchParams,
);
