// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'file_change.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `collect_created_files`, `collect_modified_files`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_file_changes`

@freezed
sealed class ChangeType with _$ChangeType {
  const ChangeType._();

  const factory ChangeType.created({required BigInt size}) = ChangeType_Created;
  const factory ChangeType.deleted() = ChangeType_Deleted;
  const factory ChangeType.modified({
    required PlatformInt64 sizeChange,
    required BigInt dlSize,
  }) = ChangeType_Modified;
}

class FileChange {
  final String filePath;
  final ChangeType change;

  const FileChange({required this.filePath, required this.change});

  @override
  int get hashCode => filePath.hashCode ^ change.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileChange &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          change == other.change;
}
