// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `finish`, `report_message`, `report_progress`, `start_for_download`, `start_without_len`

DartProgressReporter createDartProgressReporter({
  required RustStreamSink<String> reportTotalSink,
  required RustStreamSink<String> reportProgressSink,
  required RustStreamSink<String> messageSink,
  required RustStreamSink<bool> finishSink,
}) => RustLib.instance.api.crateApiProgressReportingCreateDartProgressReporter(
  reportTotalSink: reportTotalSink,
  reportProgressSink: reportProgressSink,
  messageSink: messageSink,
  finishSink: finishSink,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartProgressReporter>>
abstract class DartProgressReporter implements RustOpaqueInterface {}
