// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<OptionalAddon>> loadOptionals({
  required String repotPath,
  required String packName,
}) => RustLib.instance.api.crateApiCommandsOptionalsLoadOptionalsLoadOptionals(
  repotPath: repotPath,
  packName: packName,
);

class OptionalAddon {
  final String name;
  final bool enabled;

  const OptionalAddon({required this.name, required this.enabled});

  @override
  int get hashCode => name.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OptionalAddon &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          enabled == other.enabled;
}
