// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'optional_addon.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> saveOptionals({
  required String repotPath,
  required String packName,
  required List<OptionalAddon> optionals,
}) => RustLib.instance.api.crateApiCommandsOptionalsSaveOptionalsSaveOptionals(
  repotPath: repotPath,
  packName: packName,
  optionals: optionals,
);
