name: Release

permissions:
  id-token: write
  contents: write
  attestations: write

on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint
        run: cargo clippy -- -D warnings

  create-release:
    needs: rust-build-test-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  build-cli:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Set version
        shell: bash
        run: sed -i "s/^version = \".*\"/version = \"${GITHUB_REF_NAME#v}\"/" cli/Cargo.toml
      - name: Build and upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: pamm_cli
          # (optional) Target triple, default is host triple.
          # This is optional but it is recommended that this always be set to
          # clarify which target you are building for if macOS is included in
          # the matrix because GitHub Actions changed the default architecture
          # of macos-latest since macos-14.
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
          # (optional) On which platform to distribute the `.tar.gz` file.
          # [default value: unix]
          # [possible values: all, unix, windows, none]
          tar: unix
          # (optional) On which platform to distribute the `.zip` file.
          # [default value: windows]
          # [possible values: all, unix, windows, none]
          zip: windows
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'pamm_cli-*.tar.gz,pamm_cli-*.zip'

  package-linux:
    needs: create-release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Set version
        shell: bash
        run: sed -i "s/^version = \".*\"/version = \"${GITHUB_REF_NAME#v}\"/" cli/Cargo.toml
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Install rpm-build
        run: sudo apt-get install -y rpm
      - name: Install cargo-rpm
        run: cargo install cargo-rpm
      - name: Build cli
        run: cargo build --release --manifest-path cli/Cargo.toml
      - name: Build .deb package
        run: cargo deb --manifest-path cli/Cargo.toml
      - name: Build .rpm package
        run: cd cli && cargo rpm build
      - name: Release deb to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: target/debian/*.deb
      - name: Release rpm to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: target/release/rpmbuild/RPMS/x86_64/*.rpm
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'target/debian/*.deb,target/release/rpmbuild/RPMS/x86_64/*.rpm'

  build-gui:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: linux
            os: ubuntu-22.04
            archiveKind: tar
            archive: tar.gz
            buildDir: ui/build/linux/x64/release/bundle
          - target: windows
            os: windows-latest
            archiveKind: zip
            archive: zip
            buildDir: ui/build/windows/x64/runner/Release
    defaults:
      run:
        working-directory: ./ui
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install build deps for Linux
        if: matrix.target == 'linux'
        run: sudo apt-get install -y build-essential libgtk-3-dev
      - name: Set version
        shell: bash
        working-directory: ${{ github.workspace }}
        run: 'sed -i "s/^version: .*/version: ${GITHUB_REF_NAME#v}/" ui/pubspec.yaml'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable build
        run: flutter config --enable-${{ matrix.target }}-desktop
      - name: Build artifacts
        run: flutter build ${{ matrix.target }} --release
      - name: Package Release
        uses: sibiraj-s/action-archiver@v1
        with:
          format: '${{ matrix.archiveKind }}'
          output: 'pamm_ui-${{github.ref_name}}-${{ matrix.target }}.${{ matrix.archive }}'
          path: '${{ matrix.buildDir }}'
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: pamm_ui-${{github.ref_name}}-${{ matrix.target }}.${{ matrix.archive }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'pamm_ui-${{github.ref_name}}-${{ matrix.target }}.${{ matrix.archive }}'
