// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../progress_reporting.dart';
import 'file_change.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `diff_to_result`

Future<DiffResult> getDiff({
  required String packName,
  required String repoPath,
  required DartProgressReporter dartProgressReporter,
  required bool clearCache,
}) => RustLib.instance.api.crateApiCommandsPackSyncGetDiffGetDiff(
  packName: packName,
  repoPath: repoPath,
  dartProgressReporter: dartProgressReporter,
  clearCache: clearCache,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OpaqueDiff>>
abstract class OpaqueDiff implements RustOpaqueInterface {}

class DiffResult {
  final String packName;
  final OpaqueDiff diff;
  final bool hasChanges;
  final BigInt changeCount;
  final BigInt totalDlSize;
  final PlatformInt64 totalSizeChange;
  final Map<String, List<FileChange>> fileChanges;

  const DiffResult({
    required this.packName,
    required this.diff,
    required this.hasChanges,
    required this.changeCount,
    required this.totalDlSize,
    required this.totalSizeChange,
    required this.fileChanges,
  });

  @override
  int get hashCode =>
      packName.hashCode ^
      diff.hashCode ^
      hasChanges.hashCode ^
      changeCount.hashCode ^
      totalDlSize.hashCode ^
      totalSizeChange.hashCode ^
      fileChanges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffResult &&
          runtimeType == other.runtimeType &&
          packName == other.packName &&
          diff == other.diff &&
          hasChanges == other.hasChanges &&
          changeCount == other.changeCount &&
          totalDlSize == other.totalDlSize &&
          totalSizeChange == other.totalSizeChange &&
          fileChanges == other.fileChanges;
}
