// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../progress_reporting.dart';
import 'file_change.dart';
import 'get_diff.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<MultiDiffResult> getDiffWithParents({
  required String packName,
  required String repoPath,
  required DartProgressReporter dartProgressReporter,
  required bool clearCache,
}) => RustLib.instance.api
    .crateApiCommandsPackSyncGetDiffsWithParentsGetDiffWithParents(
      packName: packName,
      repoPath: repoPath,
      dartProgressReporter: dartProgressReporter,
      clearCache: clearCache,
    );

class MultiDiffResult {
  final List<DiffResult> results;
  final bool hasChanges;
  final BigInt totalDlSize;
  final PlatformInt64 totalSizeChange;
  final BigInt totalChangeCount;
  final BigInt changedPacks;

  const MultiDiffResult({
    required this.results,
    required this.hasChanges,
    required this.totalDlSize,
    required this.totalSizeChange,
    required this.totalChangeCount,
    required this.changedPacks,
  });

  @override
  int get hashCode =>
      results.hashCode ^
      hasChanges.hashCode ^
      totalDlSize.hashCode ^
      totalSizeChange.hashCode ^
      totalChangeCount.hashCode ^
      changedPacks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultiDiffResult &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          hasChanges == other.hasChanges &&
          totalDlSize == other.totalDlSize &&
          totalSizeChange == other.totalSizeChange &&
          totalChangeCount == other.totalChangeCount &&
          changedPacks == other.changedPacks;
}
